[theme]
base = "light"
primaryColor = "#2F80ED"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F8FF"
textColor = "#133B5C"
font = "sans serif"

[server]
port = 8501
headless = true
runOnSave = true

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"
